from tkinter import *
from PIL import Image,ImageTk
def func():
    pass
root=Tk()
root.title("SMART INDIA HACKATHON")
root.geometry("1350x800")
root.minsize(1350,800)
root.iconbitmap("q.ico.ico")
img=Image.open("j.jpg")
img=img.resize((1570,800))
photo=ImageTk.PhotoImage(img)
canvas=Canvas(root,width=1400,height=800)
canvas.create_image(0,0,image=photo,anchor="nw")
canvas.pack()
Button(root,text="<<BACK",command=func,font="comicsansms 10 bold").place(x=5,y=650)
Button(root,text="NEXT",command=func,font="default 15 bold").place(x=600,y=650)
Label(root,text="SCHOOL DETAIL FORM",font="default 25 bold",fg="red").place(x=510,y=33)
svar=StringVar()
pvar=StringVar()
scidvar=StringVar()
scaddvar=StringVar()
statevar=StringVar()
distvar=StringVar()
blockvar=StringVar()
mailvar=StringVar()
typevar=StringVar()
yearvar=StringVar()
a=Entry(root,textvariable=svar,font="courier 10 bold")
a.place(x=800,y=100)
a.focus_force()
b=Entry(root,textvariable=pvar,font="courier 10 bold")
b.place(x=800,y=260)
c=Entry(root,textvariable=scidvar,font="courier 10 bold")
c.place(x=800,y=340)
d=Entry(root,textvariable=mailvar,font="courier 10 bold")
d.place(x=800,y=420)
e=Entry(root,textvariable=typevar,font="courier 10 bold")
e.place(x=800,y=500)
f=Entry(root,textvariable=yearvar,font="courier 10 bold")
f.place(x=800,y=580)
g=Entry(root,textvariable=scaddvar,font="courier 10 bold")
g.place(x=800,y=180)
#this is different
a1=Label(root,text="SCHOOL NAME",font="courier 20 bold")
a1.place(x=400,y=100)
a1=Label(root,text="SCHOOL UNIQUE ID ",font="courier 20 bold")
a1.place(x=400,y=180)
a1=Label(root,text="PRINCIPLE NAME",font="courier 20 bold")
a1.place(x=400,y=260)
a1=Label(root,text="SCHOOL ADDRESS",font="courier 20 bold")
a1.place(x=400,y=340)
a1=Label(root,text="MAIL ID",font="courier 20 bold")
a1.place(x=400,y=420)
a1=Label(root,text="TYPE OF SCHOOL",font="courier 20 bold")
a1.place(x=400,y=500)
a1=Label(root,text="YEAR OF ESTABLISHMENT",font="courier 20 bold")
a1.place(x=400,y=580)
#different
clicked=StringVar()
clicked.set("STATE")
clicked2=StringVar()
clicked2.set("DISTRICT")
clicked3=StringVar()
clicked3.set("BLOCK")
drop=OptionMenu(root,clicked,"MP" )
drop2=OptionMenu(root,clicked2,"GWALIOR")
drop3=OptionMenu(root,clicked3,"MORAR","DABRA","BHITARWAR","GHATIGAON")
drop.place(x=1000,y=340)
drop2.place(x=1080,y=340)
drop3.place(x=1180,y=340)
root.mainloop()