from tkinter import *
from PIL import Image,ImageTk
def time():
    from time import strftime
    string = strftime('%H:%M:%S %p')
    lbl.config(text=string)
    lbl.after(1000, time)
def date():
    from datetime import datetime
    now = datetime.now()
    timestamp = datetime.timestamp(now)
    date_time = datetime.fromtimestamp(timestamp)
    d = date_time.strftime("%d %B, %Y")
    lbl2.config(text=d.upper())
def func():
    global root
    root.destroy()
    def func1():
        global root
        root.destroy()
        def func():
            pass
        root = Tk()
        root.title("SMART INDIA HACKATHON")
        root.geometry("1350x800")
        root.minsize(1350, 800)
        root.iconbitmap("q.ico.ico")
        root.wm_attributes("-transparentcolor", 'grey')
        img = Image.open("govern.jpg")
        img = img.resize((1370, 700))
        photo = ImageTk.PhotoImage(img)
        canvas = Canvas(root, width=1400, height=700)
        canvas.create_image(0, 0, image=photo, anchor="nw")
        canvas.pack()
        lbl2 = Label(root, text="SEARCH  SCHOOLS  BY", font=('calibri', 25, 'bold'), foreground='red')
        lbl2.place(x=550, y=40)
        lbl2 = Label(root, text="STATE", font=('calibri', 25, 'bold'), foreground='black')
        lbl2.place(x=350, y=140)
        lbl2 = Label(root, text="DISTRICT", font=('calibri', 25, 'bold'), foreground='black')
        lbl2.place(x=340, y=240)
        lbl2 = Label(root, text="BLOCK", font=('calibri', 25, 'bold'), foreground='black')
        lbl2.place(x=350, y=340)
        Button(root, text="SEARCH", command=func, font="comicsansms 20 bold", bg="red").place(x=590, y=460)
        svar = StringVar()
        pvar = StringVar()
        scidvar = StringVar()
        a = Entry(root, textvariable=svar, font="courier 20 bold", selectborderwidth=4)
        a.place(x=700, y=145)
        a.focus_force()
        b = Entry(root, textvariable=pvar, font="courier 20 bold")
        b.place(x=700, y=250)
        c = Entry(root, textvariable=scidvar, font="courier 20 bold")
        c.place(x=700, y=345)
        root.mainloop()
    def func2():
        global root
        root.destroy()
        def func7():
            global root
            root.destroy()
            def func9():
                global root
                root.destroy()
                def func77():
                    global root
                    root.destroy()
                    def func09():
                        global root
                        import tkinter.messagebox as tksmg
                        tksmg.showinfo("CONFIRMATION","DETAILS HAVE BEEN SAVED")
                        root.destroy()
                    root = Tk()
                    root.title("SMART INDIA HACKATHON")
                    root.geometry("1350x800")
                    root.minsize(1350, 800)
                    root.iconbitmap("q.ico.ico")
                    img = Image.open("j.jpg")
                    img = img.resize((1570, 800))
                    photo = ImageTk.PhotoImage(img)
                    canvas = Canvas(root, width=1400, height=800)
                    canvas.create_image(0, 0, image=photo, anchor="nw")
                    canvas.pack()
                    Button(root, text="<<BACK", command=func, font="comicsansms 10 bold").place(x=5, y=650)
                    Button(root, text="SAVE", command=func09, font="default 15 bold").place(x=600, y=650)
                    Label(root, text="SCHOOL DETAIL FORM", font="default 25 bold", fg="red").place(x=510, y=33)
                    svar = StringVar()
                    pvar = StringVar()
                    scidvar = StringVar()
                    scaddvar = StringVar()
                    statevar = StringVar()
                    distvar = StringVar()
                    blockvar = StringVar()
                    mailvar = StringVar()
                    typevar = StringVar()
                    yearvar = StringVar()
                    grovar = StringVar()
                    midvar = StringVar()
                    teapvar = StringVar()
                    teatvar = StringVar()
                    toipvar = StringVar()
                    toitvar = StringVar()

                    a = Entry(root, textvariable=svar, font="courier 10 bold")
                    a.place(x=500, y=100)
                    a.focus_force()
                    i = Entry(root, textvariable=pvar, font="courier 10 bold")
                    i.place(x=500, y=160)
                    b = Entry(root, textvariable=scidvar, font="courier 10 bold")
                    b.place(x=500, y=220)
                    j = Entry(root, textvariable=teapvar, font="courier 10 bold")
                    j.place(x=850, y=220)
                    k = Entry(root, textvariable=teatvar, font="courier 10 bold")
                    k.place(x=1180, y=220)
                    c = Entry(root, textvariable=scaddvar, font="courier 10 bold")
                    c.place(x=500, y=280)
                    d = Entry(root, textvariable=mailvar, font="courier 10 bold")
                    d.place(x=500, y=340)
                    e = Entry(root, textvariable=typevar, font="courier 10 bold")
                    e.place(x=500, y=400)
                    f = Entry(root, textvariable=yearvar, font="courier 10 bold")
                    f.place(x=500, y=460)
                    l = Entry(root, textvariable=toipvar, font="courier 10 bold")
                    l.place(x=850, y=460)
                    m = Entry(root, textvariable=toitvar, font="courier 10 bold")
                    m.place(x=1180, y=460)

                    # this is different
                    a1 = Label(root, text="AREA OF SCHOOL", font="courier 20 bold")
                    a1.place(x=100, y=100)
                    a1 = Label(root, text="NUMBER OF STUDENTS", font="courier 20 bold")
                    a1.place(x=100, y=160)
                    a1 = Label(root, text="NUMBER OF TEACHER", font="courier 20 bold")
                    a1.place(x=100, y=220)
                    a1 = Label(root, text="OTHER STAFF", font="courier 20 bold")
                    a1.place(x=100, y=280)
                    a1 = Label(root, text="NUMBER OF LABS", font="courier 20 bold")
                    a1.place(x=100, y=340)
                    a1 = Label(root, text="WATER PURIFIER", font="courier 20 bold")
                    a1.place(x=100, y=400)
                    a1 = Label(root, text="TOILET", font="courier 20 bold")
                    a1.place(x=100, y=460)
                    a1 = Label(root, text="GROUND", font="courier 20 bold")
                    a1.place(x=100, y=520)
                    a1 = Label(root, text="MID- DAY MEAL", font="courier 20 bold")
                    a1.place(x=100, y=580)
                    a1 = Label(root, text="PERMANENT ", font="courier 15 bold")
                    a1.place(x=1040, y=220)
                    a1 = Label(root, text="TEMPORARY", font="courier 15 bold")
                    a1.place(x=700, y=220)
                    a1 = Label(root, text="GIRLS  ", font="courier 15 bold")
                    a1.place(x=1040, y=460)
                    a1 = Label(root, text="BOYS", font="courier 15 bold")
                    a1.place(x=700, y=460)
                    varr = IntVar()
                    radio = Radiobutton(root, text="YES", variable=varr, value=1, font="comicsamsms 15")
                    radio.place(x=500, y=520)
                    radio = Radiobutton(root, text="NO", variable=varr, value=2, font="comicsamsms 15")
                    radio.place(x=590, y=520)
                    varr2 = IntVar()
                    radio1 = Radiobutton(root, text="YES", variable=varr2, value=1, font="comicsamsms 15")
                    radio1.place(x=500, y=590)
                    radio1 = Radiobutton(root, text="NO", variable=varr2, value=2, font="comicsamsms 15")
                    radio1.place(x=590, y=590)
                    root.mainloop()
                root = Tk()
                root.title("SMART INDIA HACKATHON")
                root.geometry("1350x800")
                root.minsize(1350, 800)
                root.iconbitmap("q.ico.ico")
                img = Image.open("j.jpg")
                img = img.resize((1570, 800))
                photo = ImageTk.PhotoImage(img)
                canvas = Canvas(root, width=1400, height=800)
                canvas.create_image(0, 0, image=photo, anchor="nw")
                canvas.pack()
                Button(root, text="<<BACK", command=func, font="comicsansms 10 bold").place(x=5, y=650)
                Button(root, text="NEXT", command=func77, font="default 15 bold").place(x=600, y=650)
                Label(root, text="SCHOOL DETAIL FORM", font="default 25 bold", fg="red").place(x=510, y=33)
                svar = StringVar()
                pvar = StringVar()
                scidvar = StringVar()
                scaddvar = StringVar()
                statevar = StringVar()
                distvar = StringVar()
                blockvar = StringVar()
                mailvar = StringVar()
                typevar = StringVar()
                yearvar = StringVar()
                a = Entry(root, textvariable=svar, font="courier 10 bold")
                a.place(x=800, y=100)
                a.focus_force()
                b = Entry(root, textvariable=pvar, font="courier 10 bold")
                b.place(x=800, y=260)
                c = Entry(root, textvariable=scidvar, font="courier 10 bold")
                c.place(x=800, y=340)
                d = Entry(root, textvariable=mailvar, font="courier 10 bold")
                d.place(x=800, y=420)
                e = Entry(root, textvariable=typevar, font="courier 10 bold")
                e.place(x=800, y=500)
                f = Entry(root, textvariable=yearvar, font="courier 10 bold")
                f.place(x=800, y=580)
                g = Entry(root, textvariable=scaddvar, font="courier 10 bold")
                g.place(x=800, y=180)
                # this is different
                a1 = Label(root, text="SCHOOL NAME", font="courier 20 bold")
                a1.place(x=400, y=100)
                a1 = Label(root, text="SCHOOL UNIQUE ID ", font="courier 20 bold")
                a1.place(x=400, y=180)
                a1 = Label(root, text="PRINCIPLE NAME", font="courier 20 bold")
                a1.place(x=400, y=260)
                a1 = Label(root, text="SCHOOL ADDRESS", font="courier 20 bold")
                a1.place(x=400, y=340)
                a1 = Label(root, text="MAIL ID", font="courier 20 bold")
                a1.place(x=400, y=420)
                a1 = Label(root, text="TYPE OF SCHOOL", font="courier 20 bold")
                a1.place(x=400, y=500)
                a1 = Label(root, text="YEAR OF ESTABLISHMENT", font="courier 20 bold")
                a1.place(x=400, y=580)
                # different
                clicked = StringVar()
                clicked.set("STATE")
                clicked2 = StringVar()
                clicked2.set("DISTRICT")
                clicked3 = StringVar()
                clicked3.set("BLOCK")
                drop = OptionMenu(root, clicked, "MP")
                drop2 = OptionMenu(root, clicked2, "GWALIOR")
                drop3 = OptionMenu(root, clicked3, "MORAR", "DABRA", "BHITARWAR", "GHATIGAON")
                drop.place(x=1000, y=340)
                drop2.place(x=1080, y=340)
                drop3.place(x=1180, y=340)
                root.mainloop()
            root = Tk()
            root.title("SMART INDIA HACKATHON")
            root.geometry("1350x800")
            root.minsize(1350, 800)
            root.iconbitmap("q.ico.ico")
            img = Image.open("MM.jpg")
            img = img.resize((1570, 800))
            photo = ImageTk.PhotoImage(img)
            canvas = Canvas(root, width=1400, height=800)
            canvas.create_image(0, 0, image=photo, anchor="nw")
            canvas.pack()
            Button(root, text="<<BACK", command=func, font="comicsansms 10 bold").place(x=5, y=650)
            Button(root, text="SCHOOL DETAILS", command=func9, font="default 25 bold").place(x=540, y=273)
            Button(root, text="MAINTENANCE REQUEST", command=func, font="default 25 bold").place(x=475, y=373)
            Button(root, text="UPDATE", command=func, font="default 25 bold").place(x=620, y=473)
            root.mainloop()
        root = Tk()
        root.title("SMART INDIA HACKATHON")
        root.geometry("1350x800")
        root.minsize(1350, 800)
        root.iconbitmap("q.ico.ico")
        img = Image.open("JAO.jpg")
        img = img.resize((1370, 800))
        photo = ImageTk.PhotoImage(img)
        canvas = Canvas(root, width=1400, height=700)
        canvas.create_image(0, 0, image=photo, anchor="nw")
        canvas.pack()
        Label(root, text="USERNAME", bg="white", fg="blue", font="courier 30 bold", relief=RAISED).place(x=420, y=270)
        Label(root, text="PASSWORD", bg="white", fg="blue", font="courier 30 bold", relief=RAISED).place(x=420, y=360)
        Button(root, text="<<BACK", command=func, font="comicsansms 10 bold").place(x=5, y=650)
        strr = StringVar()
        strr2 = StringVar()
        e1 = Entry(root, textvariable=strr, font="courier 30 bold", fg="red")
        e1.place(x=640, y=273)
        e1.focus_force()
        e2 = Entry(root, textvariable=strr2, font="courier 30 bold")
        e2.place(x=640, y=360)
        e2.focus_force()
        Button(root, text="LOGIN", command=func7, font="default 15 bold").place(x=590, y=473)
        Button(root, text="SIGN UP", command=func, font="default 15 bold").place(x=720, y=473)
        root.mainloop()
    root = Tk()
    root.title("SMART INDIA HACKATHON")
    root.geometry("1350x800")
    root.minsize(1350, 800)
    root.iconbitmap("q.ico.ico")
    root.wm_attributes("-transparentcolor", 'grey')
    img = Image.open("rashtra.jpg")
    img = img.resize((1370, 700))
    photo = ImageTk.PhotoImage(img)
    canvas = Canvas(root, width=1400, height=700)
    canvas.create_image(0, 0, image=photo, anchor="nw")
    canvas.pack()
    Button(root, text="GOVERNMENT OFFICIALS", command=func1, bg="white", fg="blue", font="courier 25 bold",
           activebackground="orange", activeforeground="black", relief=RAISED, borderwidth=15).place(x=205, y=510)
    Button(root, text="SCHOOL ADMINISTRATION", command=func2, bg="white", fg="blue", font="courier 25 bold",
           activebackground="orange", activeforeground="black", relief=RAISED, borderwidth=15).place(x=710, y=510)
    Button(root, text="<<BACK", command=func1, font="comicsansms 10 bold", bg="red", fg="white").place(x=10, y=660)
    Button(root, text="STUDENT SERVICES", command=func1, font="comicsansms 10 bold", fg="white", bg="red").place(x=1190,
                                                                                                                y=660)
    lbl2 = Label(root, font=('calibri', 25, 'bold'), foreground='black', background="white")
    lbl2.place(x=1100, y=550)
    root.mainloop()
root=Tk()
root.title("SMART INDIA HACKATHON")
root.geometry("1350x800")
root.minsize(1350,800)
root.iconbitmap("q.ico.ico")
img=Image.open("maxx2.jpeg")
img=img.resize((1370,700))
photo=ImageTk.PhotoImage(img)
canvas=Canvas(root,width=1400,height=700)
canvas.create_image(0,0,image=photo,anchor="nw")
canvas.pack()
Button(root,text="ENTER Ne-VA PORTAL ",command=func,fg="blue",font="default 20 bold",activebackground="orange",activeforeground="black",relief=SUNKEN,borderwidth=15,bg="white").place(x=530,y=560)
lbl2 = Label(root, font=('calibri', 25, 'bold'),foreground='black',background="white")
lbl2.place(x=1100,y=550)
date()
lbl = Label(root, font=('calibri', 10, 'bold'),background='white',foreground='black')
lbl.place(x=1190,y=590)
time()
root.mainloop()